version: '2.1'
services:
  airdcpp:
    container_name: airdcpp-smb
    build: .
    volumes:
      - ./airdcpp:/.airdcpp
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - UMASK=${UMASK:-0022}
      - SMB_HOST=example.com
      - SMB_SHARE=home
      - SMB_USERNAME=admin
      - SMB_PASSWORD=admin
    hostname: airdcpp-smb
    cap_add:
      - SYS_ADMIN 
      - DAC_READ_SEARCH
    ports:
      - ${HTTP_PORT:-80}:5600
      - ${HTTPS_PORT:-443}:5601
      - ${TCP_PORT:-21248}:${TCP_PORT:-21248}
      - ${UDP_PORT:-21248}:${UDP_PORT:-21248}/udp
      - ${TLS_PORT:-21249}:${TLS_PORT:-21249}